const theme = {
  colors: {
    black: '#000000',
    gray: '#404040',
    lightGray: '#909090',
    red: '#D32F2F',
    white: '#FFFFFF',
    error: '#DD5C42',
    success: '#358A57',
    blue: '#2196F3',
  },
  fonts: {
    regular: 'Nunito-Regular',
    italic: 'Nunito-Italic',
    bold: 'Nunito-Bold',
    boldItalic: 'Nunito-BoldItalic',
    black: 'Nunito-Black',
    blackItalic: 'Nunito-BlackItalic',
    extraBold: 'Nunito-ExtraBold',
    extraBoldItalic: 'Nunito-ExtraBoldItalic',
    extraLight: 'Nunito-ExtraLight',
    extraLightItalic: 'Nunito-ExtraLightItalic',
    light: 'Nunito-Light',
    lightItalic: 'Nunito-LightItalic',
    medium: 'Nunito-Medium',
    mediumItalic: 'Nunito-MediumItalic',
    semiBold: 'Nunito-SemiBold',
    semiBoldItalic: 'Nunito-SemiBoldItalic',
  },
  fontSizes: {
    xsmall: '12px',
    small: '14px',
    regular: '16px',
    medium: '18px',
    large: '20px',
    xlarge: '24px',
    question: '32px',
    logo: '44px',
  },
};

export default theme;
