const theme = {
  colors: {
    black: '#000000',
    blue: '#2196F3',
    burntOrange: '#DD5C42',
    darkGray: '#6A6A6A',
    gray: '#404040',
    green: '#358A57',
    lighterGray: '#D9D9D9',
    lightGray: '#909090',
    red: '#D32F2F',
    transparentGray: '#F1F1F1',
    turquoise: '#1B6470',
    white: '#FFFFFF',
  },
  fonts: {
    regular: 'Nunito-Regular',
    italic: 'Nunito-Italic',
    bold: 'Nunito-Bold',
    boldItalic: 'Nunito-BoldItalic',
    black: 'Nunito-Black',
    blackItalic: 'Nunito-BlackItalic',
    extraBold: 'Nunito-ExtraBold',
    extraBoldItalic: 'Nunito-ExtraBoldItalic',
    extraLight: 'Nunito-ExtraLight',
    extraLightItalic: 'Nunito-ExtraLightItalic',
    light: 'Nunito-Light',
    lightItalic: 'Nunito-LightItalic',
    medium: 'Nunito-Medium',
    mediumItalic: 'Nunito-MediumItalic',
    semiBold: 'Nunito-SemiBold',
    semiBoldItalic: 'Nunito-SemiBoldItalic',
  },
  fontSizes: {
    xsmall: '12px',
    small: '14px',
    regular: '16px',
    medium: '18px',
    large: '20px',
    xlarge: '24px',
    xxlarge: '28px',
    question: '30px',
    logo: '52px',
  },
};

export default theme;
