export default [
  'What is your partner incredibly good at?',
  "What's something important you've never told your partner?",
  'What is a fun tradition you would like to start with your partner?',
  'If you could go on any trip next year, what would it be?',
  'If your partner were to gift you a fully "you" day, what would it look like?',
  'What is a small thing your partner does that makes you happy?',
  "What warm childhood memory comes to mind that your partner doesn't know?",
  'What was your first impression of your partner, and how has it changed?',
  'What important lesson has this relationship taught you?',
  'What are some things you find most sexy in your partner?',
  'How have your dynamics changed, grown, or evolved since meeting?',
  'What qualities do you most admire in your partner?',
  'If you could choose any superpower to enhance your relationship, what would it be?',
  'What is something you want more of in your daily life?',
  "If you could pass three of your partner's genes along to your kids, what would they be?",
  'How do you both handle disagreements or conflicts?',
  'What three countries would you love to spend 3+ months in before you die?',
  'What shared goal would you like to achieve with your partner?',
  'What is something you admire about your partner?',
  'What is a funny or quirky habit of your partner that makes you happy?',
  'What is the ultimate dream vacation you want to take with your partner?',
  "What's your favorite date you've been on together?",
  "What's something very unique that you love about your partner?",
  'How do you prefer to manage stress in your relationship?',
  'What is your favorite outfit that your partner wears?',
  'If you could take three university classes what would you take?',
  'What is your favorite thing about your partner?',
  'What new habit would you really love to adopt together?',
  'Who are three of your heroes or inspirations and why?',
  'What do you want to do with your partner the very next time you see each other?',
  'If you could go together to see 1-3 musicians live, who would they be?',
  'What is your favorite memory of your partner?',
  'What does your absolute perfect day look like?',
  'What are some things that keep your romance alive and healthy?',
  "What are two dates you'd like to go on?",
  'What is something you very deeply wish you had more time for daily or weekly?',
  "What is something new you'd like to try together?",
  "What's something intimate you want to try with your partner?",
  "What is something you want to tell your partner that you're really sorry for?",
  'What is your most cherished tradition, celebration, or ritual as a couple?',
  'What is something you want your partner to teach you?',
  'What three things do you appreciate most about your partner?',
  'What is something you want to do with your partner?',
  'What do you most love doing for your partner?',
  'What does your dream house look like?',
  'Which friends do you wish you would hang out with more often together?',
  'What movie would you like to watch together with some popcorn and hot cocoa?',
  'How do you show love and affection to each other?',
  'What outdoor activity would you love to do together next week?',
  'What is something you want to learn about your partner?',
  'What have been three of your proudest moments?',
  'What do you really want to do this weekend?',
  'How has your partner positively influenced your life?',
  'Where would you love to live with together for 3 months next year?',
  'What do you think your partner wants more of?',
  "How have you supported each other's goals?",
  'What challenge have you overcome and how has it changed your relationship?',
  'What have you learned about love and relationships from being with your partner?',
  'Which dish or treat has your partner made that you miss badly',
  'What activity, hobby, or sport have you never done and would love to try together?',
  "What is the best piece of advice you've received about relationships?",
  'What friend do you wish you would personally reconnect with?',
];
